# Enhanced NMEA Simulator Configuration with Network Outputs

simulation:
  duration: 300  # 5 minutes
  time_factor: 1.0  # Real-time
  start_time: null  # Use current time

vessel:
  name: "Network Test Vessel"
  initial_position:
    latitude: 37.7749   # San Francisco Bay
    longitude: -122.4194
  initial_speed: 12.0   # knots
  initial_heading: 90.0 # degrees true (East)

movement:
  speed_variation: 3.0     # knots
  course_variation: 15.0   # degrees
  position_noise: 0.00001  # degrees (~1 meter)

sentences:
  - type: GGA
    talker_id: GP
    rate: 1.0  # Hz
    enabled: true
  
  - type: RMC
    talker_id: GP
    rate: 1.0  # Hz
    enabled: true

outputs:
  - type: file
    enabled: true
    path: "nmea_network_output.log"
    append: false
    auto_flush: true
    rotation_size_mb: 10
    max_files: 5
  
  - type: tcp
    enabled: true
    host: "0.0.0.0"
    port: 10110
    max_clients: 5
    client_timeout: 30.0
    send_timeout: 5.0
  
  - type: udp
    enabled: true
    host: "255.255.255.255"
    port: 10111
    broadcast: true
    send_timeout: 1.0

  - type: serial
    enabled: true # Set to false to disable this output
    port: "/dev/pts/5"  # Example for Linux. Windows: "COM1", macOS: "/dev/cu.usbserial-XYZ"
    baudrate: 9600
    bytesize: "EIGHTBITS" # Or 5, 6, 7, "FIVEBITS", "SIXBITS", "SEVENBITS"
    parity: "PARITY_NONE" # Or "PARITY_EVEN", "PARITY_ODD", "PARITY_MARK", "PARITY_SPACE"
    stopbits: "STOPBITS_ONE" # Or 1.5, 2, "STOPBITS_ONE_POINT_FIVE", "STOPBITS_TWO"
    timeout: 1.0          # Read timeout in seconds (float or null)
    write_timeout: 1.0    # Write timeout in seconds (float or null)
    # Optional settings:
    # rtscts: false         # Enable RTS/CTS hardware flow control
    # dsrdtr: false         # Enable DSR/DTR hardware flow control
    # xonxoff: false        # Enable XON/XOFF software flow control
    # exclusive: true       # Request exclusive access to the port (POSIX only)
    # send_interval: 0.0    # Minimum seconds between sends (0 for no delay)
    # reconnect_delay: 5.0  # Seconds to wait before trying to reconnect
    # max_reconnect_attempts: 5 # Number of reconnect attempts (-1 for infinite)
    # line_ending: "\r\n"   # Characters to append to each NMEA sentence (e.g., "\n", "\r\n")
